---
- name: restart wireguard
  ansible.builtin.systemd:
    name: "wg-quick@{{ vault_wg_interface }}"
    state: restarted
    daemon_reload: yes

- name: stop wireguard
  ansible.builtin.systemd:
    name: "wg-quick@{{ vault_wg_interface }}"
    state: stopped

- name: reload ufw
  ansible.builtin.shell: ufw reload
