---
- name: Verify Traefik ingress controller
  hosts: kuber_small_planes
  become: true
  gather_facts: true
  serial: 1
  tags:
    - kubernetes
    - k8s
    - traefik
    - ingress
    - verify
    - addon
  vars_files:
    - vault_secrets.yml
  vars:
    traefik_operation: verify
  roles:
    - traefik
