---
- name: Remove Traefik ingress controller
  hosts: kuber_small_planes
  become: true
  gather_facts: true
  serial: 1
  tags:
    - kubernetes
    - k8s
    - traefik
    - ingress
    - remove
    - addon
  vars_files:
    - vault_secrets.yml
  vars:
    traefik_operation: remove
  roles:
    - traefik
