---
galaxy_info:
  author: [your-username]
  description: Install and configure MetalLB for Kubernetes (BGP/Layer2)
  company: null
  license: MIT
  min_ansible_version: 2.16
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - kubernetes
    - metallb
    - loadbalancer
    - bgp
dependencies: []
