---
- name: Restart unbound
  ansible.builtin.systemd:
    name: unbound
    state: restarted
  when: not ansible_check_mode

- name: Reload unbound
  ansible.builtin.systemd:
    name: unbound
    state: reloaded
  when: not ansible_check_mode
