---
galaxy_info:
  author: linroot
  description: NFS CSI driver for Kubernetes with dynamic provisioning
  company: null
  license: MIT
  min_ansible_version: 2.16

  platforms:
    - name: Debian
      versions:
        - bookworm
        - bullseye
    - name: Ubuntu
      versions:
        - noble
        - jammy
        - focal

  galaxy_tags:
    - kubernetes
    - k8s
    - nfs
    - csi
    - storage
    - driver

dependencies: []
