---
- name: Check if folders mount exist
  ansible.builtin.stat:
    path: "{{ item.mount_point }}"
  loop: "{{ folders_list }}"
  register: folder_check
  ignore_errors: true
  changed_when: false

- name: Skip folder creation if skip_folder_check is true
  ansible.builtin.debug:
    msg: "Skipping folder check for {{ item.item.mount_point }}"
  when:
    - item.stat.exists
    - skip_folder_check | default(false)
  loop: "{{ folder_check.results }}"

- name: Fail if folders exist and not skipping checks
  ansible.builtin.fail:
    msg: "ERROR: The folder '{{ item.item.mount_point }}' already exists. Please remove it or choose a different path."
  when:
    - item.stat.exists
    - not skip_folder_check | default(false)
  loop: "{{ folder_check.results }}"
  run_once: true
