galaxy_info:
  author: [your-username]
  description: Configure NFS client mounts
  company: null
  license: MIT
  min_ansible_version: 2.16

  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Arch
      versions:
        - all

  galaxy_tags:
    - storage
    - nfs
    - filesystem
    - mount

dependencies: []
