---
verify_test_namespace: "kuber-verify-test"
verify_test_pod_image: "nginx:alpine"
verify_test_pod_port: "80"
verify_timeout_seconds: "300"
verify_sleep_seconds: "5"
verify_retry_count: "20"
verify_dns_service: "[k8s-service]"
verify_external_hostname: "[external-hostname]"
verify_node_dns_probe_enabled: true
verify_node_dns_probe_domain: "{{ verify_dns_service }}"
verify_node_dns_probe_image: "busybox:1.36"
verify_node_dns_probe_retries: "20"
verify_node_dns_probe_delay: "3"
verify_worker_label_selector: "node-role.kubernetes.io/worker"
verify_dns_probe_pod_prefix: "dns-probe"
