---
skip_folder_check: true

wg_cidr_guard_operation: "install"
wg_cidr_guard_interface: "wg99"
wg_cidr_guard_required_cidr: "[metallb-vip-cidr]"
wg_cidr_guard_check_interval: "2min"
wg_cidr_guard_check_on_boot_delay: "2min"
wg_cidr_guard_script_path: "/usr/local/libexec/wg-cidr-guard.sh"
wg_cidr_guard_service_name: "wg-cidr-guard"
wg_cidr_guard_service_unit: "wg-cidr-guard.service"
wg_cidr_guard_timer_unit: "wg-cidr-guard.timer"
wg_cidr_guard_run_on_install: true
