---
galaxy_info:
  author: linroot
  description: Install and manage cert-manager via Helm
  company: null
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - kubernetes
    - cert-manager
    - tls
    - helm

dependencies: []
