---
install_zsh: true

zsh_oh_my_zsh_repo: "https://github.com/ohmyzsh/ohmyzsh.git"
zsh_oh_my_zsh_version: "master"

zsh_powerlevel10k_repo: "https://github.com/romkatv/powerlevel10k.git"
zsh_powerlevel10k_version: "master"

zsh_autosuggestions_repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
zsh_autosuggestions_version: "master"

zsh_syntax_highlighting_repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
zsh_syntax_highlighting_version: "master"

zsh_fast_syntax_highlighting_repo: "https://github.com/zdharma-continuum/fast-syntax-highlighting.git"
zsh_fast_syntax_highlighting_version: "master"
