---
galaxy_info:
  author: [your-username]
  description: Configure FRR as a BGP router for MetalLB
  company: null
  license: MIT
  min_ansible_version: 2.16
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - bgp
    - frr
    - routing
    - kubernetes
    - metallb
dependencies: []
