---
galaxy_info:
  author: linroot
  description: Install and manage Traefik ingress controller via Helm
  company: null
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - kubernetes
    - ingress
    - traefik
    - helm

dependencies: []
