---
galaxy_info:
  author: [your-username]
  description: Initialize Kubernetes control plane with kubeadm and Calico CNI
  company: null
  license: MIT
  min_ansible_version: 2.16

  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy

  galaxy_tags:
    - kubernetes
    - k8s
    - control-plane
    - kubeadm
    - calico

dependencies: []
