---
galaxy_info:
  author: linroot
  description: Keepalived VRRP for FRR BGP router high availability
  company: null
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
  galaxy_tags:
    - networking
    - bgp
    - keepalived
    - vrrp
    - high_availability
    - frr

dependencies: []
