---
galaxy_info:
  author: [your-username]
  description: HAProxy configuration for Kubernetes API server load balancing
  company: null
  license: MIT
  min_ansible_version: 2.16

  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy

  galaxy_tags:
    - kubernetes
    - haproxy
    - loadbalancer
    - networking

dependencies: []
