---
galaxy_info:
  author: linroot
  description: Install, verify, and remove Kubernetes Node Feature Discovery manifests
  company: null
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - kubernetes
    - nfd
    - node_feature_discovery
dependencies: []
