---
galaxy_info:
  author: linroot
  description: Install and configure Flannel CNI for Kubernetes (VXLAN over WireGuard)
  company: null
  license: MIT
  min_ansible_version: 2.16
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - kubernetes
    - flannel
    - cni
    - networking
    - vxlan
    - wireguard
dependencies: []
