galaxy_info:
  author: [your-username]
  description: Install Docker and Docker Compose on Debian and Arch-based systems
  company: null
  license: MIT
  min_ansible_version: 2.16

  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Arch
      versions:
        - all

  galaxy_tags:
    - containers
    - docker
    - runtime
    - compose

dependencies: []
